### ISSUE TITLE
Questionable quality of the puzzles

### ISSUE THREAD

**Issue by abjunk07** [t103z/chess-tactics-pgn#1]
Hoe do you check them?
For example this one:
[Event "Rated Blitz game"]
[Site "https://lichess.org/zY14tLJJ"]
[Date "????.??.??"]
[Round "?"]
[White "RonaldFranco"]
[Black "A_R_A_K_E_L_Y_A_N"]
[Result "1-0"]
[BlackElo "1601"]
[BlackRatingDiff "-13"]
[ECO "C02"]
[FEN "6k1/p5pp/8/P2N4/8/4p3/RP3rPP/2bK4 b - - 3 30"]
[Opening "French Defense: Advance Variation, Nimzowitsch System"]
[SetUp "1"]
[Termination "Normal"]
[TimeControl "360+2"]
[UTCDate "2014.04.23"]
[UTCTime "19:07:56"]
[WhiteElo "1529"]
[WhiteRatingDiff "+13"]

30... Bxb2 31. Nxe3 Bc1 32. Rxf2 Bxe3 1-0

**Comment by xinyangz** [comment]
You load them with a pgn library, for example [python-chess](https://python-chess.readthedocs.io/en/latest/pgn.html).

Example code:
```python
import chess
import chess.pgn as pgn

def load_puzzle(pgn_handle):
    """
    Load a single puzzle from pgn_file.
    @param pgn_handle: file handle for your pgn puzzle file
    """
    board = chess.Board()
    game = chess.pgn.read_game(pgn_handle)
    if game is None:
        return None, None
    fen = game.headers['FEN']
    board.set_fen(fen)
    if len(list(game.mainline_moves())) == 0:
        return "empty", "empty"
    if len(list(game.mainline_moves())) < 2:
        return board, list(game.mainline_moves())[0]
    for j, mv in enumerate(game.mainline_moves()):
        if j == 0:
            board.push(mv)
        if j == 1:
            return board, mv

# load from file_name
puzzles = []
with open(file_name) as f:
    while True:
        board, mv = load_puzzle(f)
        if board is None:
            break
        elif board == "empty":
            continue
        puzzles.append((board, mv))
```

**Comment by abjunk07** [comment]
This is not my question. The puzzle itself does not make sense. There is no reason for Black to make the suggested move, it was a blunder.
So my question is, how do you select puzzles for you collection and how you verify that the moves are the best.

**Comment by xinyangz** [comment]
You should refer to the [puzzle generator](https://github.com/vitogit/pgn-tactics-generator) on how these puzzles are generated.

**Comment by abjunk07** [comment]
Puzzle #1:
[Event "0708 49919"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "solver"]
[Result "*"][SetUp "1"]
[FEN "2kr4/1p1r1p2/2p1p2p/8/P1P1Rp2/8/1P3PPP/R5K1 w KQkq - 0 1"]

1.Rxf4 Rd1+ 2.Rxd1 Rxd1# *

How can castle flags be KQkq  when both kings are not in the initial positions??

**Comment by abjunk07** [comment]
In other words you do not check the quality of your puzzles and are not responsible for the errors?
You should explain it in your READ.ME
